### ISSUE TITLE
Files being overwritten

### ISSUE THREAD

**Issue by compl3x-41** [ricardorodrigues-ca/zoom-recording-downloader#10] opened 2021-02-08 09:28 UTC
When the script downloads a meeting that has more than 1 recording 'group' it overwrites the files as file name is the same.

I think what is happening, as you can see in the picture which shows the Zoom Meeting, it downloads 'Recording 1' (2 files, 5 MB) then downloads 'Recording 2' (2 files, 106 MB) and overwrites the first Recording 1.

Could be solved by checking if file is already there, and adding a count to the end of file name? Not sure if you could just add 'Recording 1 or 2' to the end of filename from what info Zoom provides.

![img](https://user-images.githubusercontent.com/78727177/107200544-bcc41780-69ef-11eb-8654-a607655ff53d.jpg)

**Comment by compl3x-41** [comment] 2021-02-08 11:01
I have just noticed, this also happens when there are two meetings with the same exact file name and time, not just for recordings.

**Comment by pexio** [comment] 2021-08-01 22:18
Yes I have the same issue.
It seems to be a duplicate of #4 

Here's and example of how the returned data from the Zoom API looks when there's two recordings , 
```
[
    {
        "uuid": "MACq2MTqSQu3AKiRXjD26w==",
        "id": 87850923136,
        "account_id": "dj1sj-wrQgKSkAebOCkTaw",
        "host_id": "AT4hjUY3Q4SgVVEqKz-qPg",
        "topic": "Q&A",
        "type": 8,
        "start_time": "2021-06-23T06:30:35Z",
        "timezone": "Europe/Istanbul",
        "duration": 48,
        "total_size": 100308646,
        "recording_count": 4,
        "share_url": "https://us02web.zoom.us/rec/share/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "recording_files":
        [
            {
                "id": "5de9ebff-3096-4d14-811b-b48e57fbffad",
                "meeting_id": "MACq2MTqSQu3AKiRXjD26w==",
                "recording_start": "2021-06-23T06:30:37Z",
                "recording_end": "2021-06-23T07:04:46Z",
                "file_type": "MP4",
                "file_extension": "MP4",
                "file_size": 1929768,
                "play_url": "https://us02web.zoom.us/rec/play/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "download_url": "https://us02web.zoom.us/rec/download/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "status": "completed",
                "recording_type": "shared_screen_with_speaker_view"
            },
            {
                "id": "6f19d306-cca6-4b43-89f6-4ef0e12a0445",
                "meeting_id": "MACq2MTqSQu3AKiRXjD26w==",
                "recording_start": "2021-06-23T06:30:37Z",
                "recording_end": "2021-06-23T07:04:46Z",
                "file_type": "M4A",
                "file_extension": "M4A",
                "file_size": 1669061,
                "play_url": "https://us02web.zoom.us/rec/play/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "download_url": "https://us02web.zoom.us/rec/download/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "status": "completed",
                "recording_type": "audio_only"
            },
            {
                "id": "c6d9fd4e-1cb5-4aa8-9cf2-d269664d4bd5",
                "meeting_id": "MACq2MTqSQu3AKiRXjD26w==",
                "recording_start": "2021-06-23T07:04:50Z",
                "recording_end": "2021-06-23T07:51:58Z",
                "file_type": "MP4",
                "file_extension": "MP4",
                "file_size": 51711679,
                "play_url": "https://us02web.zoom.us/rec/play/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "download_url": "https://us02web.zoom.us/rec/download/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "status": "completed",
                "recording_type": "shared_screen_with_speaker_view"
            },
            {
                "id": "f85404d1-d978-4f51-89c9-79d7872eeeb0",
                "meeting_id": "MACq2MTqSQu3AKiRXjD26w==",
                "recording_start": "2021-06-23T07:04:50Z",
                "recording_end": "2021-06-23T07:51:58Z",
                "file_type": "M4A",
                "file_extension": "M4A",
                "file_size": 44998138,
                "play_url": "https://us02web.zoom.us/rec/play/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "download_url": "https://us02web.zoom.us/rec/download/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "status": "completed",
                "recording_type": "audio_only"
            }
        ]
    }
]
```
I think we could add the recording id to the file name so that they are all unique and won't overwrite eachother

**Closed** 2021-08-03 01:59 UTC
